### ISSUE TITLE
No release since Dec. 16, 2022 ?

### ISSUE THREAD

**Issue by skywind3000** [universal-ctags/ctags-win32#38]
No release since Dec. 16, 2022 ?

**Comment by k-takata** [comment]
v6.0.0 is the latest tagged release at this moment.
As you can see, there are many daily and weekly builds after it, but they are pre-releases: https://github.com/universal-ctags/ctags-win32/releases

**Comment by skywind3000** [comment]
https://github.com/universal-ctags/ctags-win32/tags

But they have tags, which is updated regularly.

**Comment by k-takata** [comment]
The universal-ctags/ctags repository has two types of tags:
* `v6.X.Y`
  Official releases. v6.0.0 is the latest official release as of now.
* `p6.X.YYYYMMDD.0`
  Weekly (periodical) pre-releases.

This repository runs the builds daily and if the universal-ctags/ctags repository has a tag, it is used as a tag of this repository. Otherwise, a daily tag is created. So, this repository has three types of tags:
* `v6.X.Y`
  Official releases. v6.0.0 is the latest official release as of now.
* `p6.X.YYYYMMDD.0`
  Weekly (periodical) pre-releases.
* `YYYY-MM-DD/<latest_tag_name>-NN-gHHHHHHH`
  Daily builds.

If you want to use newer (but can be unstable) builds, you can use weekly or daily builds on your decision.
E.g. the recent builds didn't have the `+xpath` feature because libxml2 v2.12.0 and v2.12.1 had a [bug](https://github.com/universal-ctags/ctags/issues/3851). It is fixed in the latest builds.
